# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(449, 179)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 281, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);\n"
"border: none;\n"
"border-radius: 20px;\n"
"color: black;\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 120, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: white;\n"
"color: black;\n"
"border: 2px solid #4CAF50; /* Green */\n"
"border-radius: 20px;")
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(310, 10, 121, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setStyleSheet("QComboBox{\n"
"       background-color: rgba(0, 0, 0, .2);\n"
"        border: none;\n"
"        border-radius: 20px;\n"
"    \n"
"        color: white;\n"
"        padding-left: 35px\n"
"}\n"
"\n"
"QComboBox QListView\n"
"{\n"
"    background-color: rgba(212, 212, 212);\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 80, 371, 22))
        self.lineEdit_2.setStyleSheet("background-color: rgba(255, 255, 255, 0.5);\n"
"border: none;\n"
"border-radius: 5px;\n"
"color: black;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(400, 80, 31, 21))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setStyleSheet("background-color: rgba(0, 0, 0, .2);\n"
"border: none;\n"
"border-radius: 5px;\n"
"")
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.lineEdit.setText("https://www.youtube.com/watch?v=Gon0MvppfF8")
        self.lineEdit_2.setText(str(os.getcwd()))
        self.comboBox.setCurrentText(_translate("Form", "720p"))
        self.comboBox.setItemText(0, _translate("Form", "720p"))
        self.comboBox.setItemText(1, _translate("Form", "480p"))
        self.comboBox.setItemText(2, _translate("Form", "360p"))
        self.comboBox.setItemText(3, _translate("Form", "240p"))
        self.toolButton.setText(_translate("Form", "..."))
