# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys, main
from PyQt5.QtWidgets import (QWidget, QProgressBar, QApplication)
from PyQt5.QtCore import QBasicTimer


class Example(QWidget):

    def __init__(self, finish):
        super().__init__()

        self.initUI()
        self.finish = finish


    def initUI(self):

        self.pbar = QProgressBar(self)
        self.pbar.setGeometry(30, 40, 430, 25)

        self.timer = QBasicTimer()
        self.step = 0

        self.setGeometry(300, 300, 480, 80)
        self.setWindowTitle('QProgressBar')
        self.doAction()
        self.show()


    def timerEvent(self, e):

        if self.step >= self.finish:
            self.timer.stop()
            return 0

        self.step = main.getSizeDownloadingFile()
        self.pbar.setValue(self.step)


    def doAction(self):

        if self.timer.isActive():
            self.timer.stop()
        else:
            self.timer.start(self.finish, self)


def callDownloader(finish):
    app = QApplication(sys.argv)
    ex = Example(finish)
    sys.exit(app.exec_())
